// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/17/2024, 3:54:26 PM
const configMerger = require("/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/plugins/**/*.{js,ts,mjs}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/composables/**/*.{js,ts,mjs}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/utils/**/*.{js,ts,mjs}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sneakycrow/git/The-Balance-FFXIV/balance-static/app.config.{js,ts,mjs}"] }));

module.exports = config
